apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-k8s
spec:
  selector:
    matchLabels:
      app: challenge-k8s
  template:
    metadata:
      labels:
        app: challenge-k8s
    spec:
      containers:
        - name: challenge
          image: nginx:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.2"
          ports:
            - containerPort: 80
              protocol: TCP
