apiVersion: v1
kind: Service
metadata:
  name: challenge-k8s-service
  namespace: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: challenge-k8s
  type: NodePort