apiVersion: v1
kind: Service
metadata:
  name: challenge-k8s
spec:
  selector:
    app.kubernetes.io/name: challenge-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP