name: CI/CD

on:
  push:
    branches:
      - main
  # pull_request:
  #   types: [opened, closed]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      run: npm cache clean --force && npm install

    - name: Build
      run: CI=false npm run build
    
    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker build
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/challenge-k8s:latest
    
    # - name: Pushear imagen
    #   run: | 
    #       git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #       docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/challenge-k8s:${GITHUB_REF##*/}-$git_hash .
    #       echo "Pusheamos imagen a Docker Hub"
    #       docker push ${{ secrets.DOCKER_HUB_USERNAME }}/challenge-k8s:${GITHUB_REF##*/}-$git_hash
    #       echo "::set-output name=image::${{ secrets.DOCKER_HUB_USERNAME }}/challenge-k8s:${GITHUB_REF##*/}-$git_hash"
    # - name: Actualizar versión
    #   run: |
    #       git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #       version=$(cat ./charts/helm/values.yaml | grep version: | awk '{print $2}')
    #       sed -i "s/$version/${GITHUB_REF##*/}-$git_hash/" ./charts/helm/values.yaml
          
    # - name: Pushear cambios
    #   uses: devops-infra/action-commit-push@v0.3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     commit_message: Versión actualizada